### ISSUE TITLE
Typo on "random" use.

### ISSUE THREAD

**Issue by Howld** [code51/dialoguesmith#1]
https://github.com/code51/dialoguesmith/blob/2fa7b0ddb7dcbabbb34025f48703853f0aef0985/src/Runtime/RuntimeFactory.cs#L19

**Comment by eimihar** [comment]
hi there, i am not sure what do you mean by typo.

**Comment by Howld** [comment]
The "random" variable is not to use. Sorry for my meaningless sentence.

**Comment by eimihar** [comment]
hey thanks for notifying ;)
